include ~/.config/kitty/themes/kanagawa.conf

# Font
font_family MesloLGLDZ Nerd Font Mono
bold_italic_font auto
font_size        14.0

# Window
window_padding_width 4 
hide_window_decorations yes
confirm_os_window_close 0

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
allow_remote_control yes

# Aesthetics
cursor_shape block
enable_audio_bell no


# Tab Management
tab_bar_edge top
tab_bar_align left 
tab_bar_margin_height 0.0 4.0
tab_bar_style powerline 
tab_powerline_style slanted 
tab_bar_min_tabs 2

tab_title_template "{activity_symbol} {index} {tab.active_exe}"

# keymap
# Отправлять cmd+s как Escape-последовательность
map cmd+s send_text all \x1b:write\r

# Быстрый переход по вкладкам
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map cmd+0 goto_tab 10

# Горизонтальный сплит снизу
map cmd+e launch --location=hsplit --cwd=current
