[env]
TERM = "xterm-256color"

[terminal.shell]
program = "zsh"

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.98

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = """
:Commands
"""
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002g"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "Л"
mods = "Command"


[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002u"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\""
key = "У"
mods = "Command"

[[keyboard.bindings]]
chars = """
:q
"""
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

# Сохранение в neovim
[[keyboard.bindings]]
chars = """
:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = """
:w
"""
key = "ы"
mods = "Command"

# Сохранить во всех буферах neovim
[[keyboard.bindings]]
chars = """
:wa
"""
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
:wa
"""
key = "ы"
mods = "Command|Shift"


[[keyboard.bindings]]
chars = "\u0002:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002T"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "Ц"
mods = "Command"


[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"


# [keyboard]
# bindings = [
#   # Стандартные кеймапы для копирования и вставки, по умолчанию через Ctrl + Shift + V/C
# # { key="C", mods="Control", action="Copy"},
# # { key="V", mods="Control", action="Paste"},
# #
#   # Вкл/Выкл полноэкранного режима терминала
# { key = "F", mods="Alt", action = "ToggleFullscreen" },
# { key = "А", mods="Alt", action = "ToggleFullscreen" },
#
#   # TMUX
#   # Разделение окна по горизонтали
# { key = "E",  mods = "Alt", chars = "\u0001\""},
# { key = "У",  mods = "Alt", chars = "\u0001\""},
#
#   # Созание нового окна в tmux сеансе
# { key = "Е",  mods = "Alt", chars = "\u0001c"},
# { key = "T",  mods = "Alt", chars = "\u0001c"},
#
#   # Закрытие окна в tmux
# { key = "W",  mods = "Alt", chars = "\u0001x"},
# { key = "Ц",  mods = "Alt", chars = "\u0001x"},
#
#   # Smart Tmux Manager
# { key = "Л",  mods = "Alt", chars = "\u0001T"},
# { key = "K",  mods = "Alt", chars = "\u0001T"},
#
#   # Запуск lazygit
# { key = "G",  mods = "Alt", chars = "\u0001g"},
# { key = "П",  mods = "Alt", chars = "\u0001g"},
#
#   # NVIM
#   # Сохранение буфера в Nvim
# { key = "S",  mods = "Alt", chars = ":w\u000d"},
# { key = "Ы",  mods = "Alt", chars = ":w\u000d"},
# ]
#
[terminal]
